config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_ios_rails_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations'}
  resources :posts do
    put 'report_post', to: 'posts#report_post'
    put 'feature_post', to: 'posts#feature_post'
  end
  resources :achievements
  resources :categories
  resources :users do
    put 'follow', to: 'users#follow'
    put 'unfollow', to: 'users#unfollow'
    post 'noticed', to: 'users#noticed'
    post 'tip', to: 'users#tip'
  end
  
  put 'change_password', to: 'users#change_password'
  get 'bucket_list', to: 'achievements#show_bucket_list', as: 'bucket_list'
  put 'bucket_list/add_bucket_list_item/:id', to: 'bucket_lists#add_bucket_list_item', as: 'add_bucket_list_item'
  delete 'bucket_list/remove_bucket_list_item/:id', to: 'bucket_lists#remove_bucket_list_item', as: 'remove_bucket_list_item'
  put 'posts/like/:id', to: 'posts#like_post', as: 'like_post'
  post 'comments' => 'comments#create', defaults: { format: 'js' }
  get 'explore', to: 'posts#index', as: 'explore'
  get 'join', to: 'home#join'
  get 'follow_index', to: 'posts#follow_index'

  resources :search_results do
    get :autocomplete_search_result_record_string, on: :collection  
  end

  root 'posts#follow_index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  EMAIL_FORMAT = %r(\A\S+@\S+\z)
  mount_uploader :avatar, AvatarUploader, dependent: :destroy
  acts_as_token_authenticatable
  acts_as_followable
  acts_as_follower
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :achievements, through: :posts, dependent: :destroy
  has_and_belongs_to_many :notices
  has_one :bucket_list, dependent: :destroy
  has_many :medals, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports
  
  after_create :set_bucket_list
  after_create :set_user_avatar
  after_create :create_search_result
  after_save :change_avatar
  before_destroy :remove_search_result
  before_destroy :remove_notice_links

  validates :name, presence: true 
  validates :email, format: { with: EMAIL_FORMAT }
  
  delegate :achievements, to: :bucket_list, prefix: true
  
  def set_bucket_list
    self.build_bucket_list
  end

  def create_search_result 
    SearchResult.create(record_string: name, record_id: id, record_type: 'user', record_image: avatar_url)
  end 

  def remove_search_result 
    SearchResult.where(record_type: 'user').find_by_record_id(id).destroy
  end
  
  def remove_notice_links
    Notice.where(user_id: id).destroy_all
  end
  
  def has_achievement(achievement)
    self.achievements.include? achievement
  end

  def show_post_for_achievement(achievement)
    self.posts.find_by_achievement_id(achievement.id)
  end 
  
  def set_user_avatar
    self.avatar = File.open("public/avatar.png")
    self.save!
  end
  
  def notices_has_been_showed
    notices.where(seen: nil).update_all(seen: Time.now)
  end
  
  #This should be refactored, with a state_changed like solution perhaps
  def change_avatar
    search_result = SearchResult.where(record_id: id).find_by_record_id(id)
    unless search_result == nil
      search_result.record_image = avatar_url
      search_result.save!
    end
  end
  
  def follows_user(followed_user)
    self.follows.pluck(:followable_id).include? followed_user.id
  end
  
  def follow_infos
    follow_user_names = []
    follow_user_avatars = []
    follow_user_ids = []
    self.follows.each do |follow|
      follow_user = User.find(follow.followable_id)
      follow_user_names.push(follow_user.name)
      follow_user_avatars.push(follow_user.avatar_url)
      follow_user_ids.push(follow_user.id)
    end
    [follow_user_names, follow_user_avatars, follow_user_ids]
  end

  def follower_infos
    follower_user_names = []
    follower_user_avatars = []
    follower_user_ids = []
    self.followers.each do |follower|
      follower_user = User.find(follower.id)
      follower_user_names.push(follower_user.name)
      follower_user_avatars.push(follower_user.avatar_url)
      follower_user_ids.push(follower_user.id)
    end
    [follower_user_names, follower_user_avatars, follower_user_ids]
  end

  def notice_infos
    notice_user_ids = []
    notice_user_avatars = []
    notice_messages = []
    notice_types = []
    notice_link_ids = []
    notice_seen = []
    self.notices.each do |notice|
      notice_user = User.find(notice.user_id)
      notice_user_ids.push(notice_user.id)
      notice_user_avatars.push(notice_user.avatar_url)
      notice_messages.push(notice.message)
      notice_types.push(notice.notice_type)
      notice_link_ids.push(notice.link.to_i)
      notice_seen.push(notice.seen)
    end 
    [notice_user_ids, notice_user_avatars, notice_messages, notice_types, notice_link_ids, notice_seen]
  end 
  
  def check_like_in_posts(posts)
    user_likes_post_ids = likes.pluck(:post_id)
    post_ids = posts.pluck(:id)
    like_array = []
    post_ids.each do |post_id|
      if user_likes_post_ids.include? post_id
        like_array.push(true)
      else
        like_array.push(false)
      end
    end
    like_array
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  before_action :set_user_id, only: [:follow, :unfollow, :noticed, :tip]
  acts_as_token_authentication_handler_for User

  def index
    @users = User.all
  end
  
  def show
    @posts = @user.posts.limit(20)
    @json_posts = @user.posts.limit(4)
    json_post_achievement_ids = @json_posts.pluck(:achievement_id)
    @json_achievements = Achievement.where(id: json_post_achievement_ids).sort_by { |a| json_post_achievement_ids.index(a.id) }
    @user_score = @user.posts.joins(:achievement).sum(:score)
  
    @total_achievements_count = Achievement.count
    @total_posts_count = @user.posts.count

    @week_achievements_count = Achievement.where(created_at: Time.now.beginning_of_week..Time.now).count
    @week_posts_count = @user.posts.joins(:achievement).
                          where('achievements.created_at between ? and ?',
                          Time.now.beginning_of_week, Time.now).count

    @comment = Comment.new
    @achievements = Achievement.all
    @current_user = current_user
    @user_bucketlist_achievements = @user.bucket_list.achievements
    @user_post_ids = @user.posts.pluck(:id)
    @user_achievement_ids = @user.posts.pluck(:achievement_id)
    @user_video_urls = @json_posts.map { |p| p.video_url }
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end
  
  def edit
  end
  
  def update
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def follow
    current_user.follow(@user)
    Notice.follow(current_user, @user, true)
    redirect_to :back
  end
  
  def unfollow
    current_user.stop_following(@user)
    Notice.follow(current_user, @user, false)
    redirect_to :back
  end
  
  def tip
    achievement_id = params[:achievement]
    Notice.tip(current_user, @user, achievement_id)
    redirect_to :back
  end
  
  def noticed
    @user.notices_has_been_showed
    redirect_to :back
  end
  
  def change_password
    if current_user.valid_password? params[:current_password]
      current_user.reset_password(params[:password], params[:password_confirmation])
      @result = true
    else
      @result = false
    end
  end
    
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def set_user_id
    @user = User.find(params[:user_id])
  end
  
  def user_params
    if params[:avatar] != nil
      # For iOS requests
      params.permit(:name, :avatar, :current_password, :password, :password_confirmation)
    else
      params.require(:user).permit(:name, :avatar, :current_password, :password, :hide, :share_gps)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def check_user_bucket_list(user)
    return true if user == current_user
  end
end

app/views/users/_bucket_list.html.erb
<% @user.bucket_list_achievements.each do |achievement| %>

    <%= achievement.description %>

    <% if check_user_bucket_list(@user) %>
        <%= link_to 'Ta bort', remove_bucket_list_item_path(achievement.id), id: 'remove-achievement' %>
    <% end %>

    <br>
<% end %><br>

app/views/users/_edit_avatar.html.erb
<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
    <p class="user-settings-text">Profilbild</p>
    <p class="user_avatar">
      <%= f.file_field :avatar %>
      <label for="user_avatar">Välj fil</label>
    </p>
	</div>
  <div class="field user-name">
    <p class="user-settings-text">Byt användarnamn</p>
    <%= f.text_field :name, placeholder: current_user.name %>
  </div>
  <div class="large-12 columns gps-container">
    <div class="large-4 medium-6 small-8 columns share-gps">
      <p class="user-settings-text">Dela GPS-data</p>
    </div>
    <div class="large-2 medium-4 small-4 columns gps-button">
      <label>
        <%= f.check_box :share_gps, class: 'ios-switch green bigswitch' %>
        <div class="ios-button"><div></div></div>
      </label>
    </div>
  </div>
  <div class="field">
    <%= link_to "Byt lösenord", '#', class: 'button expand success', data: {:"reveal-id" => "reveal-user-password"} %>
  </div>
  <div class="actions">
  	<%= f.submit 'Spara', class: 'button expand success' %>
  </div>
<% end %>



<div id="reveal-user-password" class="reveal-modal small medal-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
  <div class="large-10 large-centered columns">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= devise_error_messages! %>
      Byt lösenord
      <div class="field">
        <p class="user-settings-text">Nuvarande lösenord</p>
        <%= f.password_field :current_password, autocomplete: "off" %>
      </div>
      <div class="field">
        <p class="user-settings-text">Nytt lösenord</p>
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
      <div class="actions">
        <%= f.submit 'Spara', class: 'button expand success' %>
      </div>
    <% end %>
    <%= link_to "Tillbaka", user_path(current_user), remote: true, data: {:"reveal-id" => "reveal-user-options"} %>
  </div>
</div>

app/views/users/_follows.html.erb
<% if current_user.follows.count > 0 %>
	<% current_user.follows.each do |follow| %>
		<!-- follow.followable to get the users you follow -->
		<%= image_tag(follow.followable.avatar, size: '30') %>
		<%= follow.followable.name %>	
		<%= link_to 'Tipsa', user_tip_path(follow.followable, achievement: achievement), class: 'button tiny radius success tip-button', method: :post %>
		<hr class="popup-hr">
	<% end %>
<% else %>
	Du följer ingen ännu.
<% end %>

app/views/users/_notices.html.erb
<% notices.each do |notice| %>
	<% if notice.notice_type == 'tip' %>
		<% @link = achievement_path(notice.link) %>
	<% elsif notice.notice_type == 'follow' %>
		<% @link = user_path(notice.user_id)%>
	<% else %>
		<% @link = post_path(notice.link) %>
	<% end %>
	<li<% if notice.seen.nil? %> class="active"<% end %>><%= link_to notice.message, @link %></li>
<% end %>

app/views/users/edit.html.erb
<div class="medium-8 medium-centered large-8 large-centered columns">
	<h1 class="edit-user-text">Redigera Profil</h1><br/>

	<%= render 'edit_avatar' %>

	<%= link_to 'Back', users_path, class: 'button success radius expand' %>
</div>

app/views/users/index.html.erb
<div class="user-content">

    <%= render 'search_user' %>
    <br><br>

    <% @users.each do |user| %>
        <div class="users">
          <%= link_to user, class: 'test' do %>
              <div class="user-name">
                 <%= user.name %><br>
              </div>
          <% end %>
        </div>
    <% end %>

</div>

app/views/users/show.html.erb
<div class="large-10 large-centered columns user-profile radius">
	<div id="user-container">
		<div class="large-2 columns center-children">
			<div class="user-avatar">
				<%= image_tag @user.avatar, width: 140 %>
			</div>
			<% unless @user == current_user %>
				<div class="follow-actions">
					<% if current_user.follows_user(@user) %>
						<%= link_to 'Sluta följ', user_unfollow_path(@user), method: :PUT, class: 'button expand success follow follow-button' %>
					<% else %>
						<%= link_to 'Följ', user_follow_path(@user), method: :PUT, class: 'button expand success follow follow-button' %>	
					<% end %>
				</div>
			<% end %>
		</div>
		<div class="large-10 columns center-children">
			<% if @user == current_user %>
				<div class="dropdown-button">
					<%= link_to icon('fi-widget user-settings'), user_path(@user), remote: true, data: {:"reveal-id" => "reveal-user-options"} %>
				</div>
			<% end %>
			<div class="user-info">
				<div class="large-4 columns user-name">
					<h3 class="profile-heading"><%= @user.name %></h3>
				</div>
				<div class="large-2 columns user-score">
					<%= @user_score %>p
				</div>
				<div class="large-2 columns user-follow">
					<%= link_to "#{@user.followers.length} följare", user_path(@user), data: {:"reveal-id" => "reveal-followers-profile"} %>
				</div>
				<div class="large-2 columns user-follow last-user-info">
					<%= link_to "Följer #{@user.follows.length}", user_path(@user), data: {:"reveal-id" => "reveal-follows-profile"} %>
				</div>
			</div>
			<div class="large-12 columns user-progress">
			 	<div class="completion-bar-profile">
			 		<script type="text/javascript">
				 		$(document).on('ready page:load', function() {
						  return $('.fill').animate({
						    width: <%=((@total_posts_count.to_f / @total_achievements_count.to_f) * 100).round(1) %> + '%'
						  }, 1000);
						});
			 		</script>
					<div class="fill">
						
					</div>
					<p class="user_profile"><%= @total_posts_count.to_s + "/" + @total_achievements_count.to_s %></p> 
	      </div>
			</div>
		</div>
	</div>
</div>

<!-- Popups -->

<div id="reveal-user-options" class="reveal-modal small medal-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<%= render partial: 'edit_avatar' %>	
</div>

<div id="reveal-followers-profile" class="reveal-modal small followers-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<div class="large-12 columns">
		<% if @user.followers.length > 0 %>
			<% @user.followers.each do |user| %>
				<%= link_to user_path(user) do %>
				  <%= image_tag(user.avatar, size: "30") %>
					<%= user.name %>
					<% unless current_user == user %>
						<% if current_user.follows_user(user) %>
							<%= link_to 'Sluta följ', user_unfollow_path(user), method: :PUT, class: 'button tiny radius success popup-follow-button' %>
						<% else %>
							<%= link_to 'Följ', user_follow_path(user), method: :PUT, class: 'button tiny radius success popup-follow-button' %>	
						<% end %>
					<% end %>
					<hr class="popup-hr">
				<% end %>
			<% end %>
		<% else %>
			<h2 class="popup-text">Den här användaren har inga följare ännu.</h2>
		<% end %>
	</div>
</div>

<div id="reveal-follows-profile" class="reveal-modal small follows-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<div class="large-12 columns">
		<% if @user.follows.length > 0 %>
			<% @user.follows.each do |user| %>
				<%= link_to user_path(user) do %>
				  <%= image_tag(user.followable.avatar, size: "30") %>		
					<%= user.followable.name %>
					<% unless current_user == user.followable %>
						<% if current_user.follows_user(user.followable) %>
							<%= link_to 'Sluta följ', user_unfollow_path(user.followable), method: :PUT, class: 'button tiny radius success popup-follow-button' %>
						<% else %>
							<%= link_to 'Följ', user_follow_path(user.followable), method: :PUT, class: 'button tiny radius success popup-follow-button' %>	
						<% end %>
					<% end %>
					<hr class="popup-hr">
				<% end %>
			<% end %>
		<% else %>
			<h2 class="popup-text">Den här användaren följer ingen ännu.</h2>
		<% end %>
	</div>
</div>

<div class="medium-12 medium-centered large-12 large-centered columns user-achievements">
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix media-container">	
	<div class="done-achievements">
<div class="medium-12 medium-centered large-12 large-centered columns">
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix media-container">	<div class="done-achievements">
			<%= render @posts %>
		</div>
	</div>
</div>
<script type="text/javascript">
	user = <%= @user.id %>;
</script>