config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_ios_rails_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations'}
  resources :posts do
    put 'report_post', to: 'posts#report_post'
    put 'feature_post', to: 'posts#feature_post'
  end
  resources :achievements
  resources :categories
  resources :users do
    put 'follow', to: 'users#follow'
    put 'unfollow', to: 'users#unfollow'
    post 'noticed', to: 'users#noticed'
    post 'tip', to: 'users#tip'
  end
  
  put 'change_password', to: 'users#change_password'
  get 'bucket_list', to: 'achievements#show_bucket_list', as: 'bucket_list'
  put 'bucket_list/add_bucket_list_item/:id', to: 'bucket_lists#add_bucket_list_item', as: 'add_bucket_list_item'
  delete 'bucket_list/remove_bucket_list_item/:id', to: 'bucket_lists#remove_bucket_list_item', as: 'remove_bucket_list_item'
  put 'posts/like/:id', to: 'posts#like_post', as: 'like_post'
  post 'comments' => 'comments#create', defaults: { format: 'js' }
  get 'explore', to: 'posts#index', as: 'explore'
  get 'join', to: 'home#join'
  get 'follow_index', to: 'posts#follow_index'

  resources :search_results do
    get :autocomplete_search_result_record_string, on: :collection  
  end

  root 'posts#follow_index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  acts_as_followable
  acts_as_follower
  belongs_to :user, touch: true
  belongs_to :achievement, counter_cache: true, touch: true
  has_many :likes, dependent: :destroy
  has_many :comments, as: :imageable, dependent: :destroy
  has_many :reports, dependent: :destroy

  before_create :check_achievement
  after_create :lower_achievement_score, :remove_from_bucketlist
  after_create :set_image
  after_save :process_video
  before_destroy :higher_achievement_score
  before_destroy :remove_notice_links

  default_scope { order('created_at DESC') }
  
  validate :image_or_video

  def has_video?
    !video.file.nil?
  end

  def check_achievement
    self.achievement.users.exclude? self.user
  end
  
  def lower_achievement_score
    if self.achievement.score != 5 && self.achievement.users.count > 1
      self.achievement.update_attributes(score: self.achievement.score - 5)
    end
  end

  def higher_achievement_score
    if self.achievement.score < 100 && self.achievement.users.count < 20
      self.achievement.update_attributes(score: self.achievement.score + 5)
    end
  end
  
  def remove_from_bucketlist
    self.user.bucket_list.achievements.destroy(self.achievement)
  end
  
  def remove_notice_links
    Notice.where(notice_type: ['comment', 'like']).where(link: id).destroy_all
  end
  
  def check_like(user)
    if self.likes.find_by_user_id(user)
      return true
    else
      return false
    end
  end

  def set_success(format, opts)
    self.success = true
  end
  
  def report_post(user)
    self.reports.create(user_id: user.id, status: 0)
  end
  
  def image_or_video
    if image.blank? && video.blank?
      errors.add(:image, "Finns ingen bild eller video")
    end
  end
  
  def process_video
    if self.video.content_type != "application/mp4" && image.url.blank? && video
      uploaded_video = FFMPEG::Movie.new("public" + self.video.url)
      uploaded_video.screenshot("public/uploads/post/video/" + self.id.to_s + "/" + self.id.to_s + ".jpg")
      uploaded_video.transcode("public/uploads/post/video/" + self.id.to_s + "/" + self.id.to_s + ".mp4")
      self.video = Rails.root.join("public/uploads/post/video/" + self.id.to_s + "/" + self.id.to_s + ".mp4").open
      self.image = File.open("public/uploads/post/video/" + self.id.to_s + "/" + self.id.to_s + ".jpg")
      self.save!
    end
  end

  #Set image from video column and remove uploaded image from video if uploaded record is an image
  def set_image
    if self.video.content_type && self.video.content_type.split('/')[0] == 'image'
      self.image = self.video
      self.remove_video!
      self.save
    end
  end

  def comments_count
    self.comments.count 
  end

  def commenter_infos
    commenter_user_names = []
    commenter_user_avatars = []
    commenter_user_ids = []
    commenter_comments = []
    self.comments.each do |comment|
      commenter_user_names.push(comment.user.name)
      commenter_user_avatars.push(comment.user.avatar_url)
      commenter_user_ids.push(comment.user.id)
      commenter_comments.push(comment.comment)
    end
    [commenter_user_names, commenter_user_avatars, commenter_user_ids, commenter_comments]
  end
  
  def like_infos
    like_user_names = []
    like_user_avatars = []
    like_user_ids = []
    self.likes.each do |like|
      like_user_names.push(like.user.name)
      like_user_avatars.push(like.user.avatar_url)
      like_user_ids.push(like.user.id)
    end
    [like_user_names, like_user_avatars, like_user_ids]
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, except: [:index, :new, :create, :follow_index, :feature_post, :report_post]
acts_as_token_authentication_handler_for User

  def index
    # index for posts after fetching
    if params[:id] and params[:follow_ids].nil? and params[:user].nil? and params[:achievement].nil? and params[:reload].nil? and params[:new].nil?
      @posts = Post.where('id < ?', params[:id]).limit(20)
      @json_posts = Post.where('id < ?', params[:id]).limit(4)
    # index for posts pre fetching
    elsif params[:id].nil? and params[:follow_ids].nil? and params[:user].nil? and params[:achievement].nil? and params[:reload].nil? and params[:new].nil?
      @posts = Post.limit(20)
      @json_posts = Post.limit(4)
    end
    
    # index for users after fetching
    if params[:user]
      @posts = User.find(params[:user]).posts.where('id < ?', params[:id]).limit(20)
      @json_posts = User.find(params[:user]).posts.where('id < ?', params[:id]).limit(4)
    end
    
    # index for follows after fetching
    if params[:follow_ids] and params[:new].nil?
      follow_ids = current_user.follows.pluck(:followable_id)
      follow_ids.push(current_user.id)
      @posts = Post.where('user_id IN (?)', follow_ids).where('id < ?', params[:id]).limit(20)
      @json_posts = Post.where('user_id IN (?)', follow_ids).where('id < ?', params[:id]).limit(4)
    end
    
    # index for achievement after fetching
    if params[:achievement]
      @posts = Achievement.find(params[:achievement]).posts.where('id < ?', params[:id]).limit(20)
      @json_posts = Achievement.find(params[:achievement]).posts.where('id < ?', params[:id]).limit(4)
    end
    
    if params[:reload]
      post_ids = params[:reload]
      updated_at = params[:updated_at]
      result = changed_posts(post_ids, updated_at)
      changed_post_ids = result[0]
      @json_posts = Post.where(id: changed_post_ids)
      unless result[1].empty?
        @deleted_post_ids = [result[1]]
      end
    end
    
    if params[:new]
      if params[:follow_ids]
        follow_ids = current_user.follows.pluck(:followable_id)
        follow_ids.push(current_user.id)
        @json_posts = Post.where('user_id IN (?)', follow_ids).where('id > ?', params[:new]).reverse
      else
        @json_posts = Post.where('id > ?', params[:new]).reverse
      end
    end

    @current_user = current_user
    @comment = Comment.new
  end
  
  def show
    @current_user = current_user
    @comment = Comment.new
    @comments = @post.comments.order("id DESC")
  end

  def new
    @post = Post.new
    @achievement_id = params[:achievement_id]
  end
  
  def like_post
    like = Like.create(user_id: current_user.id, post_id: @post.id)
    like.save
    if like.save
      Notice.like(like, true)
    else
      Notice.like(like, false)
      like = @post.likes.find_by_user_id(current_user.id)
      like.destroy
    end
    head :no_content
  end

  def edit
  end

  def create
    @post = current_user.posts.create(post_params)
    @post.likes_count = 0
    @post.status = 1
    @post.save!
    if @post.latitude == nil
      lat_lng = cookies[:lat_lng].split("|") rescue nil
      @post.latitude = lat_lng[0] rescue nil
      @post.longitude = lat_lng[1] rescue nil
      @post.save!
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @post.user_id == current_user.id || current_user.admin
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, notice: 'No permission' }
      end
    end
  end
  
  def follow_index
    # fetch all user_ids from users following current_user
    @follow_ids = current_user.follows.pluck(:followable_id)
    @follow_ids.push(current_user.id)
    @posts = Post.where('user_id IN (?)', @follow_ids).limit(20)
    @json_posts = Post.where('user_id IN (?)', @follow_ids).limit(4)
    @comment = Comment.new
    # check if no result for sending nil-params to index
    if @posts.length == 0
      follow_ids = 'nil'
    end
    respond_to do |format|
      format.html
      format.js
      format.json {
        render "index.json.jbuilder"
      }
    end
  end

  def feature_post
    @post = Post.find(params[:post_id])
    if @post.status == 1
      @post.update_attributes(status: 2)
    else 
      @post.update_attributes(status: 1)
    end
    redirect_to :back
  end 
  
  def report_post
    @post = Post.find(params[:post_id])
    @post.report_post(current_user)
    redirect_to :back
  end
  
  def changed_posts(post_ids, updated_at)
    changed_post_ids = []
    deleted_post_ids = []
    post_ids.each_with_index do |post_id, index|
      current_timestamp = Post.find(post_id).updated_at.strftime('%a, %d %b %Y %H:%M:%S') rescue nil
      old_timestamp = updated_at[index].to_datetime.strftime('%a, %d %b %Y %H:%M:%S')
      if current_timestamp != old_timestamp 
        unless current_timestamp == nil 
          changed_post_ids.push(post_id)
        else
          deleted_post_ids.push(post_id)
        end
      end
    end
    [changed_post_ids, deleted_post_ids]
  end
  
  private
  
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    if params[:image] != nil || params[:video] != nil
      # For iOS requests
      params.permit(:image, :video, :achievement_id)
    else
      params.require(:post).permit(:image, :video, :user_id, :achievement_id, :status, :comments_count)
    end
  end
  
end

  

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
		<%= f.label :message, class: 'body-text' %><br>
    	<%= f.text_field :message %><br>
	</div>
  	<div class="actions">
    	<%= f.submit class: 'button expand' %>
  	</div>
<% end %>

app/views/posts/_form.html.erb
<div class="medium-8 medium-centered large-8 large-centered columns">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field">
		<%= f.label :Bild, class: 'body-text' %>
		<%= f.file_field :image, class: 'body-text' %>
	</div>
	<div class="field">
		<%= f.label :Video, class: 'body-text' %>
		<%= f.file_field :video, class: 'body-text' %>
	</div>
	<%= f.hidden_field :achievement_id, value: @achievement_id%>
  	<div class="actions">
    	<%= f.submit "Skapa inlägg", class: 'button expand' %>
  	</div>
<% end %>
</div>

app/views/posts/_likes.html.erb
<div class="likes">
	<% if likes.count > 0 %>
		<% likes.each do |like| %>
			<%= link_to user_path(like.user) do |user| %>
					<span>
						<%= image_tag(like.user.avatar, size: '30') %>
					</span>
					<span>
						<%= like.user.name%>
					</span>
			<% end %>
			<hr class="popup-hr">
		<% end %>
	<% else %>
		Ingen har gillat detta inlägg. 
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="box col3 masonry-brick" data-id="<%= post.id %>">
	<div class="post_top">
		<div class="post_user">
			<% if post.user.avatar.length > 0 %>
				<%= link_to image_tag(post.user.avatar, width: "30px", height: "30px"), user_path(post.user)%>
			<% else %>
				<%= link_to image_tag('avatar.png', width: "30px", height: "30px"), user_path(post.user)%>
			<% end %>
			<h3><%= link_to post.user.name, user_path(post.user) %></h3>
		</div>
		<div class="score">
			<h3><%= post.achievement.score %></h3>
		</div>
	</div>
	<div class="post_image" height="<%= post.height %>px!important">
		<% if post.has_video? %>
			<%= video_tag(post.video, controls: true, autobuffer: true, width: 270, height: 350) %>
		<% else %>
			<%= image_tag(post.image, width: post.width, height: post.height, lazy: true) %>
		<% end %>
	</div>
	<div class="post_info">
		<%= link_to post, remote: true, data: {:"reveal-id" => "reveal-likes-#{post.id}"} do %>
			<div class="post-likes">
				<%= image_tag '/like-icons/like.png' %>
			</div>
			<div id="likes-counter-<%=post.id%>" class="counter-fix post-counters">
					<%= post.likes_count.to_i %>
			</div>
		<% end %>
		<%= link_to post, remote: true, id: 'comment-link', data: {:"reveal-id" => "reveal-#{post.id}"} do %>
			<div class="post-comments">
				<%= image_tag 'fi-comments.png' %>
			</div>
			<div class="counter-info-comments post-counters">
				<%= post.comments.count %>
			</div>
		<% end %>
	</div>
	<div class="achievement_description_post">
		<h3><%= link_to post.achievement.description, post.achievement %></h3>
	</div>
	<div class="post-buttons">
		<div id="like-button-<%= post.id %>">
			<ul class="button-group radius post-buttons">
			<% if user_signed_in? %>
				<% if post.check_like(current_user) %>
					<li><%= link_to image_tag('/like-icons/liked.png', id: "heart-#{post.id}" ), like_post_path(post), method: :PUT, remote: true, class: 'like', id: "like-icon-#{post.id}" %></li>
				<% else %>
					<li><%= link_to image_tag('/like-icons/like.png', id: "heart-#{post.id}" ), like_post_path(post), method: :PUT, remote: true, class: 'like', id: "like-icon-#{post.id}" %></li>
				<% end %>
				<li><%= link_to image_tag('fi-comment.png'), post, remote: true, id: 'comment-link', data: {:"reveal-id" => "reveal-#{post.id}"} %></li>
				<li><%= link_to image_tag('more-icon.png'), user_path(post.user), remote: true, data: {:"reveal-id" => "reveal-options-#{post.id}"} %></li>
			<% else %>
				<li><%= link_to image_tag('fi-heart.png'), new_user_registration_path %></li>
				<li><%= link_to image_tag('fi-comment.png'), new_user_registration_path %></li>
				<li><%= link_to image_tag('more-icon.png'), new_user_registration_path %></li>
			<% end %>
			</ul>
		</div>
	</div>
	<div id="reveal-<%=post.id%>" class="reveal-modal post-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<div class="large-6 columns media-hide">
			<div id="post">
			<div class="post_top">
				<div class="post_user">
					<% if post.user.avatar.length > 0 %>
						<%= link_to image_tag(post.user.avatar, width: "30px", height: "30px"), user_path(post.user)%>
					<% else %>
						<%= link_to image_tag('avatar.png', width: "30px", height: "30px"), user_path(post.user)%>
					<% end %>
					<h3><%= link_to post.user.name, user_path(post.user) %></h3>
				</div>
				<div class="delete-button">
					<%= link_to image_tag('dropdown.png'), user_path(post.user), remote: true, data: {:"reveal-id" => "reveal-options-#{post.id}"} %>
				</div>
				<div class="score">
					<h3><%= post.achievement.score %>p</h3>
				</div>
			</div>
				<div class="post_image_popup">
					<% if post.has_video? %>
						<%= video_tag(post.video, controls: true, autobuffer: true, width: 270, height: 350) %>
					<% else %>
						<%= image_tag(post.image, width: post.width, height: post.height, lazy: true) %>
					<% end %>
				</div>
				<div class="post_info">
					<%= link_to post, remote: true, data: {:"reveal-id" => "reveal-likes-#{post.id}"} do %>
					<div id="counter_info-<%=post.id%>" class="counter-fix">
						<%= t('likes_count', count: post.likes_count.to_i) %>
					</div>
					<% end %>
					<div class="counter-info-comments">
						<%= t('comments_count', count: post.comments.count) %>
					</div>
				</div>
			</div>
		</div>
		<div class="large-6 columns" id="comment">
			<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
			<div id="comment_list-<%= post.id %>" class="comments">
				<%= render partial: 'comments/list', object: post.comments %>
			</div>
			<div class="comment-input">
				<%= render partial: 'comments/form', object: post %>
			</div>
		</div>
	</div>
	<div id="reveal-likes-<%=post.id%>" class="reveal-modal medium-2 columns small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
		<%= render partial: 'posts/likes', object: post.likes %>
	</div>
	<div id="reveal-options-<%=post.id%>" class="reveal-modal medium-2 columns small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
		<div class="large-12 columns">
			<% unless achievement_path(post.achievement) %>
				<%= link_to 'Visa uppdrag', post.achievement %><br>
			<% end %>
			<% if user_signed_in? %>
				<% if current_user.admin %>
					<%= link_to 'Ta bort inlägg', post, method: :delete %><br>
					<%= link_to 'Feature/Unfeature', post_feature_post_path(post), method: :put %><br>
					<%= link_to 'Lägg till uppdrag i min lista', add_bucket_list_item_path(post.achievement.id), method: :put, remote: true, class: 'close-reveal-modal add-bucketlist' %><br>
					<% if current_user.following?(post.user) %>
						<%= link_to 'Sluta följ användare', user_unfollow_path(post.user), method: :put %>
					<% else %>
						<%= link_to 'Följ användare', user_follow_path(post.user), method: :put %>
					<% end %>
				<% elsif current_user == post.user %>
					<%= link_to 'Ta bort inlägg', post, method: :delete %><br>
				<% else %>
					<% unless already_in_bucket_list(post.achievement) || current_user.has_achievement(post.achievement) %>
						<%= link_to 'Lägg till uppdrag i min lista', add_bucket_list_item_path(post.achievement.id), method: :put, remote: true, class: 'close-reveal-modal add-bucketlist' %><br>
					<% end %>
					<%= link_to 'Rapportera inlägg', post_report_post_path(post), method: :put %><br>
					<% if current_user.following?(post.user) %>
						<%= link_to 'Sluta följ användare', user_unfollow_path(post.user), method: :put %>
					<% else %>
						<%= link_to 'Följ användare', user_follow_path(post.user), method: :put %>
					<% end %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'edit_form' %>

<%= link_to 'Back', posts_path, class: 'button success radius expand' %>

app/views/posts/follow_index.html.erb
<div class="medium-12 medium-centered large-12 large-centered columns">
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix media-container">
		<%= render @posts %>
	</div>
</div>
<script type="text/javascript">
    follow_ids = <%= @follow_ids %>;
</script>

app/views/posts/index.html.erb
<div class="medium-12 medium-centered large-12 large-centered columns">
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix media-container">
		<%= render @posts %>
	</div>
</div>

app/views/posts/index.js.erb
<% if @posts %>
	$('#masonry-container').append('<%= escape_javascript(render(:partial => @posts)) %>')
<% end %>

app/views/posts/new.html.erb
<script>getGeoLocation()</script>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="medium-12 medium-centered large-12 large-centered columns">
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix media-container">
		<%= render @post %>
	</div>
</div>