config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_ios_rails_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations'}
  resources :posts do
    put 'report_post', to: 'posts#report_post'
    put 'feature_post', to: 'posts#feature_post'
  end
  resources :achievements
  resources :categories
  resources :users do
    put 'follow', to: 'users#follow'
    put 'unfollow', to: 'users#unfollow'
    post 'noticed', to: 'users#noticed'
    post 'tip', to: 'users#tip'
  end
  
  put 'change_password', to: 'users#change_password'
  get 'bucket_list', to: 'achievements#show_bucket_list', as: 'bucket_list'
  put 'bucket_list/add_bucket_list_item/:id', to: 'bucket_lists#add_bucket_list_item', as: 'add_bucket_list_item'
  delete 'bucket_list/remove_bucket_list_item/:id', to: 'bucket_lists#remove_bucket_list_item', as: 'remove_bucket_list_item'
  put 'posts/like/:id', to: 'posts#like_post', as: 'like_post'
  post 'comments' => 'comments#create', defaults: { format: 'js' }
  get 'explore', to: 'posts#index', as: 'explore'
  get 'join', to: 'home#join'
  get 'follow_index', to: 'posts#follow_index'

  resources :search_results do
    get :autocomplete_search_result_record_string, on: :collection  
  end

  root 'posts#follow_index'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  has_many :users, through: :posts
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :bucket_lists
  has_many :posts, dependent: :destroy
  belongs_to :user
  
  default_scope { order('created_at DESC') }
  
  validates :description, presence: true
  
  after_create :set_score
  after_create :create_search_result

  before_destroy :remove_search_result
  before_destroy :remove_notice_links
  
  def set_score
    self.score = 100
    self.save!
  end

  def create_search_result
    SearchResult.create(record_string: description, record_id: id, record_type: 'achievement', record_image: '/achievement_icon_blue.png')
  end

  def remove_search_result 
    SearchResult.where(record_type: 'achievement').find_by_record_id(id).destroy
  end
  
  def remove_notice_links
    Notice.where(notice_type: 'tip').where(link: id).destroy_all
  end
  
  def self.generate_new_achievements
    # first file in lib/assets/not_used/
    first_file = Dir.glob("lib/assets/not_used/*").first
    File.open(first_file) do |file|
      file.each_line do |line|
        self.new(description: line.chomp, user_id: 1).save
      end
    end
    # rename and save file in used
    File.rename first_file, "lib/assets/used/#{self.first.id}"
  end
  
  def check_if_in_bucketlist(user)
    user.bucket_list.achievements.include?(self)
  end
  
  def check_if_completed(user)
    user.achievements.include?(self)
  end
  
  def check_user_post(user)
    post = self.posts.find_by_user_id(user.id)
    if post
      post.id
    else
      0
    end
  end

  def latest_posts
    image_urls = []
    post_ids = []
    self.posts.first(3).each do |post|
      image_urls.push(post.image_url(:thumb_achievement))
      post_ids.push(post.id)
    end
    [image_urls, post_ids]
  end 

  def completer_user_infos
    completer_user_ids = []
    completer_user_names = []
    completer_user_avatars = []
    self.posts.each do |post|
      completer_user_ids.push(post.user.id)
      completer_user_names.push(post.user.name)
      completer_user_avatars.push(post.user.avatar.url)
    end
    completer_user_infos = [completer_user_ids, completer_user_names, completer_user_avatars]
    completer_user_infos
  end
  
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :set_achievement, only: [:show, :edit, :update, :destroy]

  acts_as_token_authentication_handler_for User

  # GET /achievements
  # GET /achievements.json
  def index
    if params[:achievements]
      @achievements = Achievement.where('id < ?', params[:achievements]).limit(20)
      @json_achievements = Achievement.where('id < ?', params[:achievements]).limit(4)
    else
      @achievements = Achievement.limit(20)
      @json_achievements = Achievement.limit(4)
    end
    @current_user = current_user
    
    if params[:reload]
      achievement_ids = params[:reload]
      updated_at = params[:updated_at]
      @json_achievements = changed_achievements(achievement_ids, updated_at)
    end
    
    if params[:new]
      @json_achievements = Achievement.where('id > ?', params[:new]).reverse
    end

    @post = Post.new  
  end

  # GET /achievements/1
  # GET /achievements/1.json
  def show
    @current_user = current_user
    @posts = @achievement.posts.limit(20)
    @video_urls = @posts.map { |p| p.video_url }  
    @comment = Comment.new
    @post = Post.new
  end

  def show_bucket_list
    @achievements = current_user.bucket_list.achievements.limit(20)
    @post = Post.new
  end

  # GET /achievements/new
  def new
    @achievement = Achievement.new
    @categories = Category.all
  end

  # GET /achievements/1/edit
  def edit
    @categories = Category.all
  end

  # POST /achievements
  # POST /achievements.json
  def create
    @achievement = Achievement.new(achievement_params)
    respond_to do |format|
      if @achievement.save
        format.html { redirect_to @achievement, notice: 'Achievement was successfully created.' }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /achievements/1
  # PATCH/PUT /achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to @achievement, notice: 'Achievement was successfully updated.' }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achievements/1
  # DELETE /achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url, notice: 'Achievement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def changed_achievements(achievement_ids, updated_at)
    changed_achievement_ids = []
    achievement_ids.each_with_index do |achievement_id, index|
      current_timestamp = Achievement.find(achievement_id).updated_at.strftime('%a, %d %b %Y %H:%M:%S')
      old_timestamp = updated_at[index].to_datetime.strftime('%a, %d %b %Y %H:%M:%S')
      if current_timestamp != old_timestamp 
        changed_achievement_ids.push(achievement_id)
      end
    end
    achievements = Achievement.where(id: changed_achievement_ids)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def achievement_params
      params.require(:achievement).permit(:description, :score, :posts_count, category_ids: [])
    end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
  def already_in_bucket_list(achievement)
    if user_signed_in?
      current_user.bucket_list.achievements.include?(achievement)
    end
  end
end

app/views/achievements/_achievement.html.erb
<div class="achievements" data-id="<%= achievement.id %>" id="achievement-id">
  <%= link_to achievement.description, achievement, class: 'hide'  %>
	<div class="achievement_categories">
		<div class="locks">
			<% if current_user.has_achievement(achievement) %>
				<%= icon('fi-unlock locks-icon') %>
			<% else %>
				<%= icon('fi-lock locks-icon') %>
			<% end %>
		</div>
		<% if user_signed_in? %>
			<% if current_user.admin %>
				<div class="dropdown-button">
					<%= link_to image_tag('dropdown.png'), achievement_path(achievement), remote: true, data: {:"reveal-id" => "reveal-options-#{achievement.id}"} %>
				</div>
			<% end %>
		<% end %>
		<div class="score">
			<h3><%= achievement.score %>p</h3>
		</div>
	</div>
	<div class="achievement_description">
		<h3><%= link_to achievement.description, achievement %></h3>
  </div>
  <div class="achievement_posts">
    <% 3.times do |index| %>
      <% if achievement.posts[index] %> 
        <% if achievement.posts[index].has_video? %>
          <%= link_to (video_tag achievement.posts[index].video, poster: achievement.posts[index].image, size:"85x65"), achievement.posts[index] %>
        <% else %>
          <%= link_to image_tag((achievement.posts[index].image_url(:thumb_achievement) if achievement.posts[index].image?)), achievement.posts[index] %>
        <% end %>
      <% else %>
        <%= image_tag 'post.png', size: "85" %>
      <% end %>
    <% end %>
  </div>
  <div class="achievement_info">
  	<div class="achievements-counters">
  		<div class="users-completed">
        <%= link_to t('.posts_count', count: achievement.posts.count), achievement, remote: true, data: {:"reveal-id" => "reveal-users-#{achievement.id}"} %>
  		</div>
  	</div>
  	<ul class="achievement-ul">
    	<li>
				<%= link_to icon("fi-torsos-all"), achievement, remote: true, data: {:"reveal-id" => "reveal-users-#{achievement.id}"}, class: 'achievement-icons' %>
			</li>
			<li>
				<%= link_to icon("fi-share"), achievement, remote: true, data: {:"reveal-id" => "reveal-follows-#{achievement.id}"}, class: 'achievement-icons' %>
			</li>
			<li>
				<div id="achievement_<%=achievement.id%>" class="add-achievement">
					<% if user_signed_in? %>
						<% if current_user.has_achievement(achievement) %>
							<%= link_to image_tag('achievement-completed.png'), post_path(current_user.show_post_for_achievement(achievement)), class: 'achievement-icons' %>
						<% else %>
							<%= render partial: 'bucket_lists/bucket_list_actions', locals: {achievement: achievement} %>
						<% end %>
					<% end %>
			  </div>
		  </li>
		</ul>
		<% if user_signed_in? %>
			<% if current_user.has_achievement(achievement) %>
				<%= link_to 'Visa inlägg', post_path(current_user.show_post_for_achievement(achievement)), class: 'button expand success radius achievement-actions' %>
			<% else %>
				<%= form_for(@post) do |f| %>
				  <% if @post.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
				      <ul>
				      <% @post.errors.full_messages.each do |message| %>
				        <li><%= message %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>
				  <div class="field">
				    <p class="upload-post">
				      <%= f.file_field :video, id: 'upload' %>
				      <label for="upload-post">Ladda upp</label>
				    </p>
					</div>
					<%= f.hidden_field :achievement_id, value: achievement.id%>
				<% end %>
			<% end %>
		<% end %>
  </div>
	<div id="reveal-users-<%=achievement.id%>" class="reveal-modal small medium-2 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
		<div class="large-12 columns">
			<%= render partial: 'achievements/users', object: achievement.posts.pluck(:user_id) %>
		</div>
	</div>
	<div id="reveal-follows-<%=achievement.id%>" class="reveal-modal small medium-2 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
		<div class="large-12 columns">
			<%= render partial: 'users/follows', locals: {achievement: achievement} %>
		</div>
	</div>
	<div id="reveal-options-<%=achievement.id%>" class="reveal-modal small medium-2 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
		<% if user_signed_in? %>
			<% if current_user.admin? %>
				<%= link_to 'Ta bort uppdrag', achievement, method: :delete %><br>
				<%= link_to 'Editera uppdrag', edit_achievement_path(achievement) %><br>
			<% end %>
		<% end %>
	</div>
</div>

app/views/achievements/_form.html.erb
<%= form_for(@achievement) do |f| %>
  <% if @achievement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@achievement.errors.count, "error") %> prohibited this achievement from being saved:</h2>

      <ul>
      <% @achievement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description, class: 'body-text' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/achievements/_search_achievement.html.erb
<%= form_for( :achievement, html: {id: "search_achievement_form"}) do |f| %>

    <%= f.autocomplete_field :description, autocomplete_achievement_description_achievements_path,
                                     value: "", id: "search_achievement", placeholder: "Sök..." %>

<% end %>

app/views/achievements/_users.html.erb
<% if users.count > 0 %>
	<% users.each do |user| %>
		<% @achievement_user = User.find(user) %>
		<%= link_to user_path(@achievement_user) do |user| %>
			<%= image_tag(@achievement_user.avatar, size: '30') %>
			<%= @achievement_user.name %>
		<% end %>
		<hr class="popup-hr">
	<% end %>
<% else %>
	Ingen har klarat detta uppdrag. 
<% end %>

app/views/achievements/edit.html.erb
<h1>Editing Achievement</h1>

<%= render 'form' %>

<%= link_to 'Show', @achievement %> |
<%= link_to 'Back', achievements_path %>

app/views/achievements/index.html.erb
<div id="achievement-container" class="achievement-content medium-12 medium-centered large-12 large-centered columns media-container">
   <%= render @achievements %>
</div>

app/views/achievements/index.js.erb
<% if @achievements %>
  $('#achievement-container').append('<%= escape_javascript(render(:partial => @achievements)) %>')
<% end %>

app/views/achievements/new.html.erb
<h1>New Achievement</h1>

<%= render 'form' %>

<%= link_to 'Back', achievements_path %>

app/views/achievements/show.html.erb
<div class="medium-12 medium-centered large-12 large-centered columns">
	<div id="achievement-container" class="media-container">
		<%= render @achievement %>
	</div>
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix media-container">
		<div class="done-achievements">
			<%= render @posts %>
		</div>
	</div>
</div>
<script type="text/javascript">
	achievement = <%= @achievement.id %>;
</script>

app/views/achievements/show_bucket_list.html.erb
<div id="achievement-container" class="achievement-content medium-12 medium-centered large-12 large-centered columns media-container">
   <%= render @achievements %>
</div>