config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_ios_rails_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations'}
  resources :posts do
    put 'report_post', to: 'posts#report_post'
    put 'feature_post', to: 'posts#feature_post'
  end
  resources :achievements
  resources :categories
  resources :users do
    put 'follow', to: 'users#follow'
    put 'unfollow', to: 'users#unfollow'
    post 'noticed', to: 'users#noticed'
    post 'tip', to: 'users#tip'
  end
  
  put 'change_password', to: 'users#change_password'
  get 'bucket_list', to: 'achievements#show_bucket_list', as: 'bucket_list'
  put 'bucket_list/add_bucket_list_item/:id', to: 'bucket_lists#add_bucket_list_item', as: 'add_bucket_list_item'
  delete 'bucket_list/remove_bucket_list_item/:id', to: 'bucket_lists#remove_bucket_list_item', as: 'remove_bucket_list_item'
  put 'posts/like/:id', to: 'posts#like_post', as: 'like_post'
  post 'comments' => 'comments#create', defaults: { format: 'js' }
  get 'explore', to: 'posts#index', as: 'explore'
  get 'join', to: 'home#join'
  get 'follow_index', to: 'posts#follow_index'

  resources :search_results do
    get :autocomplete_search_result_record_string, on: :collection  
  end

  root 'posts#follow_index'

end

app/views/layouts/_user_menu.html.erb
<li class="has-dropdown user-notices"<% if current_page? user_path(current_user) %> class="active"<% end %>>
	<% if current_user.avatar? %>
		<%= link_to image_tag(current_user.avatar, size: '39'), '#' %>
	<% else %>
		<%= link_to image_tag('avatar_white.png', size: '37'), '#' %>
	<% end %>
	<ul class="dropdown drop-left">
		<li>
			<% if current_user.avatar? %>
				<%= link_to image_tag(current_user.avatar, size: '39') + ' Min profil', user_path(current_user) %>
			<% else %>
				<%= link_to image_tag('avatar_white.png', size: '37') + ' Min profil', user_path(current_user) %>
			<% end %>
		</li>
		<li>
			<%= link_to "Inställningar", user_path(current_user), data: {:"reveal-id" => "reveal-user-settings"} %>
		</li>
		<li>
			<%= link_to "Följare", user_path(current_user), data: {:"reveal-id" => "reveal-followers"} %>
		</li>
		<li>
			<%= link_to "Följer", user_path(current_user), data: {:"reveal-id" => "reveal-follows"} %>
		</li>
		<li>
			<%= link_to "Hitta vänner", user_path(current_user), data: {:"reveal-id" => "reveal-find-friends"} %>
		</li>
		<li>
			<%= link_to "Logga ut", destroy_user_session_path, method: 'DELETE' %>
		</li>
	</ul>
</li>


<!-- User settings modal -->

<div id="reveal-user-settings" class="reveal-modal small followers-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<div class="large-12 columns">
		<%= render partial: 'users/edit_avatar' %>
	</div>
</div>


<!-- Followers modal -->

<div id="reveal-followers" class="reveal-modal small followers-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<div class="large-12 columns">
		<% if current_user.followers.length > 0 %>
			<% current_user.followers.each do |user| %>
				<%= link_to user_path(user) do %>
				  <%= image_tag(user.avatar, size: "30") %>
					<%= user.name %>
					<% unless current_user == user %>
						<% if current_user.follows_user(user) %>
							<%= link_to 'Sluta följ', user_unfollow_path(user), method: :PUT, class: 'button tiny radius success popup-follow-button' %>
						<% else %>
							<%= link_to 'Följ', user_follow_path(user), method: :PUT, class: 'button tiny radius success popup-follow-button' %>	
						<% end %>
					<% end %>
					<hr class="popup-hr">
				<% end %>
			<% end %>
		<% else %>
			<h2 class="popup-text">Du har har inga följare ännu.</h2>
		<% end %>
	</div>
</div>


<!-- Follows modal -->

<div id="reveal-follows" class="reveal-modal small follows-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<div class="large-12 columns">
		<% if current_user.follows.length > 0 %>
			<% current_user.follows.each do |user| %>
				<%= link_to user_path(user.followable) do %>
				  <%= image_tag(user.followable.avatar, size: "30") %>
					<%= user.followable.name %>
					<% unless current_user == user.followable %>
						<% if current_user.follows_user(user.followable) %>
							<%= link_to 'Sluta följ', user_unfollow_path(user.followable), method: :PUT, class: 'button tiny radius success popup-follow-button' %>
						<% else %>
							<%= link_to 'Följ', user_follow_path(user.followable), method: :PUT, class: 'button tiny radius success popup-follow-button' %>	
						<% end %>
					<% end %>
					<hr class="popup-hr">
				<% end %>
			<% end %>
		<% else %>
			<h2 class="popup-text">Du följer ingen ännu.</h2>
		<% end %>
	</div>
</div>


<!-- Find friends modal -->

<div id="reveal-find-friends" class="reveal-modal small followers-modal large-10 medium-10 columns" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<a class="close-reveal-modal close-fix" aria-label="Close">&#215;</a>
	<div class="large-12 columns">
		Hitta vänner
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title><%= content_for?(:title) ? yield(:title) : "Veckokampen" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
	<div class="fixed bottom-bordered" height="45px">
		<nav class="top-bar" data-topbar role="navigation">
		  <ul class="title-area">
		    <li class="name">
		      <h1><%= link_to "Veckokampen", root_path %></h1>
		    </li>
		     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
		    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		  </ul>

		  <section class="top-bar-section">
		    <!-- Right Nav Section -->
			<% if user_signed_in? %>
			    <ul class="right">
			    	<li<% if current_page? root_path %> class="active"<% end %>><%= link_to image_tag('home_icon_white.png', size: '40'), root_path %></li>
					  <li<% if current_page? explore_path %> class="active"<% end %>><%= link_to image_tag('explore_icon_white.png', size: '42'), explore_path %></li>
				  	<li<% if current_page? achievements_path %> class="active"<% end %>><%= link_to image_tag('achievement_icon_white.png', size: '39'), achievements_path %></li>
						<li <% if current_page? bucket_list_path %> class="active"<% end %>><%= link_to image_tag('bucket-list-icon.png', size: '37'), bucket_list_path %></li>
						<ul class="right">
				  		<%= render partial: 'layouts/user_menu' %>
				  	</ul>
						<ul class="right" data-options="is_hover: false">
				      <li id="notices-<%= current_user.id%>" class="notices has-dropdown notice-dropdown">
				      	<%= link_to (
					      	if @notices.any?
					      		image_tag('notice_icon_red.png', size: '37') + @notices.count.to_s
					      	else 
					      		image_tag('notice_icon_white.png', size: '37')
					      	end
				      		), '#', id: 'notishref' 
				      	%>

				        <ul class="dropdown dropdown-notices">
				          <%= render partial: 'users/notices', object: current_user.notices.limit(10) %>
				        </ul>
				      </li>
				  	</ul>
			    </ul>
			<% else%>
				<ul class="right">
   					<li><a href="#" id="sign_in">Logga in</a></li>
    				<li><a href="#" id="register">Bli medlem</a></li>
				</ul>
			<% end %>
		    <!-- Left Nav Section -->
		    <ul class="left">
				<%= render 'search_results/search'%>
		    </ul>
		  </section>
		</nav>
	</div><br>
    <%= yield %>
  </body>
</html>